# Generated by Django 4.2.1 on 2023-05-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_photo', models.ImageField(upload_to='base/static/assets/images')),
                ('detail_photo_1', models.ImageField(upload_to='base/static/assets/images')),
                ('detail_photo_2', models.ImageField(upload_to='base/static/assets/images')),
                ('detail_photo_3', models.ImageField(upload_to='base/static/assets/images')),
                ('plant_name', models.CharField(max_length=255)),
                ('previous_price', models.IntegerField()),
                ('current_price', models.IntegerField()),
                ('stock_count', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
