# Generated by Django 4.2 on 2023-05-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='cover_photo',
            field=models.ImageField(upload_to='base/plants/assets/images'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='detail_photo_1',
            field=models.ImageField(upload_to='base/plants/assets/images'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='detail_photo_2',
            field=models.ImageField(upload_to='base/plants/assets/images'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='detail_photo_3',
            field=models.ImageField(upload_to='base/plants/assets/images'),
        ),
    ]
