# Generated by Django 4.2 on 2023-06-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Delivered', 'DELIVERED'), ('Canceled', 'CANCELED')], default='Pending', max_length=15),
        ),
    ]
