# Generated by Django 4.2.1 on 2023-05-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='detail_photo_1',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='detail_photo_2',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='detail_photo_3',
        ),
        migrations.AddField(
            model_name='plant',
            name='additiona_image',
            field=models.FileField(blank=True, null=True, upload_to='assets/images'),
        ),
        migrations.AddField(
            model_name='plant',
            name='featured_image',
            field=models.FileField(blank=True, null=True, upload_to='assets/images'),
        ),
    ]
