# Generated by Django 4.2.1 on 2023-05-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('seller', 'seller'), ('customer', 'customer')], default='customer', max_length=15),
        ),
    ]
