# Generated by Django 4.2.1 on 2023-05-15 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_plant_cover_photo_remove_plant_detail_photo_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='additional_images')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='base.plant')),
            ],
        ),
    ]
