# Generated by Django 4.2.1 on 2023-05-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Seller', 'seller'), ('Customer', 'customer')], default='customer', max_length=15),
        ),
    ]
