# Generated by Django 4.2.1 on 2023-05-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_additionalimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='additiona_image',
            new_name='additional_image',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='previous_price',
            new_name='discount',
        ),
        migrations.AlterField(
            model_name='additionalimage',
            name='image',
            field=models.ImageField(upload_to='assets/images'),
        ),
    ]
