# Generated by Django 4.2 on 2023-05-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_product_additional_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_images',
            field=models.ImageField(blank=True, null=True, upload_to='assets/images'),
        ),
    ]
